set number		" Show line numbers
set linebreak		" Break lines at word (requires Wrap lines)
set showbreak=+++	" Wrap-broken line prefix
set textwidth=100	" Line wrap (number of cols)
set visualbell		" Use visual bell (no beeping)
 
set hlsearch		" Highlight all search results
set smartcase		" Enable smart-case search
set ignorecase		" Always case-insensitive
set incsearch		" Searches for strings incrementally
 
set autoindent		" Auto-indent new lines
set cindent		" Use 'C' style program indenting
set expandtab		" Use spaces instead of tabs
set shiftwidth=4	" Number of auto-indent spaces
set smartindent		" Enable smart-indent
set smarttab		" Enable smart-tabs
set softtabstop=4	" Number of spaces per Tab
 
set ruler		" Show row and column ruler information
 
set autochdir		" Change working directory to open buffer

set undolevels=1000		" Number of undo levels
set backspace=indent,eol,start	" Backspace behaviour

let mapleader="§"

syntax on
syntax enable
filetype plugin indent on

" syntax
au BufRead,BufNewFile *.as set syntax=cpp "angelscript
au BufRead,BufNewFile *.angelscript set syntax=cpp "angelscript
au BufRead,BufNewFile *.htm set filetype=html

" Share osx clipboard
set clipboard+=unnamedplus

execute pathogen#infect()
